# Docs: https://docs.github.com/en/code-security/dependabot

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      include: scope
      prefix: "CLDR-15539 gh:"
    assignees:
      - btangmu
      - srl295
    reviewers:
      - btangmu
      - srl295

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      include: scope
      prefix: "CLDR-15539 j:"
    assignees:
      - btangmu
      - srl295
    reviewers:
      - btangmu
      - srl295
